sonar.projectKey=JosueTije_TaskHub
sonar.organization=josuetije
sonar.projectName=TaskHub

# Fuentes analizadas
sonar.sources=Backend/src,FrontEnd/src

# Tests
sonar.tests=Backend/src/__tests__,FrontEnd/src/__tests__

# Excluir generados y dependencias
sonar.exclusions=**/node_modules/**,**/dist/**,**/prisma/migrations/**,**/*.test.js,**/*.test.ts,**/*.test.tsx

# Cobertura (si se genera en CI)
sonar.javascript.lcov.reportPaths=Backend/coverage/lcov.info,FrontEnd/coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
